//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `AudioSubject.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let AudioSystem = _ModuleRegistry.module("AudioSystem");

    Slice.defineSequence(AudioSystem, "AudioDataHelper", "Ice.ByteHelper", true);

    Slice.defineSequence(AudioSystem, "StringSeqHelper", "Ice.StringHelper", false);

    const iceC_AudioSystem_AudioObserver_ids = [
        "::AudioSystem::AudioObserver",
        "::Ice::Object"
    ];

    AudioSystem.AudioObserver = class extends Ice.Object
    {
    };

    AudioSystem.AudioObserverPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(AudioSystem.AudioObserver, AudioSystem.AudioObserverPrx, iceC_AudioSystem_AudioObserver_ids, 0,
    {
        "receiveAudio": [, , , , , [["AudioSystem.AudioDataHelper"]], , , , ],
        "incomingCall": [, , , , , [[7]], , , , ],
        "callAccepted": [, , , , , [[7]], , , , ],
        "callRejected": [, , , , , [[7]], , , , ],
        "callEnded": [, , , , , [[7]], , , , ]
    });

    const iceC_AudioSystem_AudioSubject_ids = [
        "::AudioSystem::AudioSubject",
        "::Ice::Object"
    ];

    AudioSystem.AudioSubject = class extends Ice.Object
    {
    };

    AudioSystem.AudioSubjectPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(AudioSystem.AudioSubject, AudioSystem.AudioSubjectPrx, iceC_AudioSystem_AudioSubject_ids, 0,
    {
        "attach": [, , , , , [[7], ["AudioSystem.AudioObserverPrx"]], , , , ],
        "detach": [, , , , , [[7]], , , , ],
        "sendAudio": [, , , , , [[7], ["AudioSystem.AudioDataHelper"]], , , , ],
        "getConnectedUsers": [, , , , ["AudioSystem.StringSeqHelper"], , , , , ],
        "startCall": [, , , , , [[7], [7]], , , , ],
        "acceptCall": [, , , , , [[7], [7]], , , , ],
        "rejectCall": [, , , , , [[7], [7]], , , , ],
        "hangup": [, , , , , [[7], [7]], , , , ],
        "getPendingIncomingCalls": [, , , , ["AudioSystem.StringSeqHelper"], [[7]], , , , ],
        "getPendingAcceptedCalls": [, , , , ["AudioSystem.StringSeqHelper"], [[7]], , , , ],
        "getPendingRejectedCalls": [, , , , ["AudioSystem.StringSeqHelper"], [[7]], , , , ],
        "getPendingEndedCalls": [, , , , ["AudioSystem.StringSeqHelper"], [[7]], , , , ]
    });
    exports.AudioSystem = AudioSystem;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
