//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `AudioSubject.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package AudioSystem;

public interface AudioObserverPrx extends com.zeroc.Ice.ObjectPrx
{
    default void receiveAudio(byte[] data)
    {
        receiveAudio(data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void receiveAudio(byte[] data, java.util.Map<String, String> context)
    {
        _iceI_receiveAudioAsync(data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> receiveAudioAsync(byte[] data)
    {
        return _iceI_receiveAudioAsync(data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> receiveAudioAsync(byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_receiveAudioAsync(data, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_receiveAudioAsync(byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "receiveAudio", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    default void incomingCall(String fromUser)
    {
        incomingCall(fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void incomingCall(String fromUser, java.util.Map<String, String> context)
    {
        _iceI_incomingCallAsync(fromUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> incomingCallAsync(String fromUser)
    {
        return _iceI_incomingCallAsync(fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> incomingCallAsync(String fromUser, java.util.Map<String, String> context)
    {
        return _iceI_incomingCallAsync(fromUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_incomingCallAsync(String iceP_fromUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "incomingCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                 }, null);
        return f;
    }

    default void callAccepted(String fromUser)
    {
        callAccepted(fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void callAccepted(String fromUser, java.util.Map<String, String> context)
    {
        _iceI_callAcceptedAsync(fromUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> callAcceptedAsync(String fromUser)
    {
        return _iceI_callAcceptedAsync(fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> callAcceptedAsync(String fromUser, java.util.Map<String, String> context)
    {
        return _iceI_callAcceptedAsync(fromUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_callAcceptedAsync(String iceP_fromUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "callAccepted", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                 }, null);
        return f;
    }

    default void callRejected(String fromUser)
    {
        callRejected(fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void callRejected(String fromUser, java.util.Map<String, String> context)
    {
        _iceI_callRejectedAsync(fromUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> callRejectedAsync(String fromUser)
    {
        return _iceI_callRejectedAsync(fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> callRejectedAsync(String fromUser, java.util.Map<String, String> context)
    {
        return _iceI_callRejectedAsync(fromUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_callRejectedAsync(String iceP_fromUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "callRejected", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                 }, null);
        return f;
    }

    default void callEnded(String fromUser)
    {
        callEnded(fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void callEnded(String fromUser, java.util.Map<String, String> context)
    {
        _iceI_callEndedAsync(fromUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> callEndedAsync(String fromUser)
    {
        return _iceI_callEndedAsync(fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> callEndedAsync(String fromUser, java.util.Map<String, String> context)
    {
        return _iceI_callEndedAsync(fromUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_callEndedAsync(String iceP_fromUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "callEnded", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioObserverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), AudioObserverPrx.class, _AudioObserverPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioObserverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), AudioObserverPrx.class, _AudioObserverPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioObserverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), AudioObserverPrx.class, _AudioObserverPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioObserverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), AudioObserverPrx.class, _AudioObserverPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static AudioObserverPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, AudioObserverPrx.class, _AudioObserverPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static AudioObserverPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, AudioObserverPrx.class, _AudioObserverPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default AudioObserverPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (AudioObserverPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default AudioObserverPrx ice_adapterId(String newAdapterId)
    {
        return (AudioObserverPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default AudioObserverPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (AudioObserverPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default AudioObserverPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (AudioObserverPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default AudioObserverPrx ice_invocationTimeout(int newTimeout)
    {
        return (AudioObserverPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default AudioObserverPrx ice_connectionCached(boolean newCache)
    {
        return (AudioObserverPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default AudioObserverPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (AudioObserverPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AudioObserverPrx ice_secure(boolean b)
    {
        return (AudioObserverPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default AudioObserverPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (AudioObserverPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AudioObserverPrx ice_preferSecure(boolean b)
    {
        return (AudioObserverPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default AudioObserverPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (AudioObserverPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default AudioObserverPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (AudioObserverPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default AudioObserverPrx ice_collocationOptimized(boolean b)
    {
        return (AudioObserverPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default AudioObserverPrx ice_twoway()
    {
        return (AudioObserverPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default AudioObserverPrx ice_oneway()
    {
        return (AudioObserverPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default AudioObserverPrx ice_batchOneway()
    {
        return (AudioObserverPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default AudioObserverPrx ice_datagram()
    {
        return (AudioObserverPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default AudioObserverPrx ice_batchDatagram()
    {
        return (AudioObserverPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default AudioObserverPrx ice_compress(boolean co)
    {
        return (AudioObserverPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default AudioObserverPrx ice_timeout(int t)
    {
        return (AudioObserverPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default AudioObserverPrx ice_connectionId(String connectionId)
    {
        return (AudioObserverPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default AudioObserverPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (AudioObserverPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::AudioSystem::AudioObserver";
    }
}
