//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `AudioSubject.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package AudioSystem;

/** @hidden */
public class _AudioSubjectPrxI extends com.zeroc.Ice._ObjectPrxI implements AudioSubjectPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
