//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `AudioSubject.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package AudioSystem;

public interface AudioSubject extends com.zeroc.Ice.Object
{
    void attach(String userId, AudioObserverPrx obs, com.zeroc.Ice.Current current);

    void detach(String userId, com.zeroc.Ice.Current current);

    void sendAudio(String fromUser, byte[] data, com.zeroc.Ice.Current current);

    void startCall(String fromUser, String toUser, com.zeroc.Ice.Current current);

    void acceptCall(String fromUser, String toUser, com.zeroc.Ice.Current current);

    void rejectCall(String fromUser, String toUser, com.zeroc.Ice.Current current);

    void hangup(String fromUser, String toUser, com.zeroc.Ice.Current current);

    String[] getConnectedUsers(com.zeroc.Ice.Current current);

    String[] getPendingIncomingCalls(String userId, com.zeroc.Ice.Current current);

    String[] getPendingAcceptedCalls(String userId, com.zeroc.Ice.Current current);

    String[] getPendingRejectedCalls(String userId, com.zeroc.Ice.Current current);

    String[] getPendingEndedCalls(String userId, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::AudioSystem::AudioSubject",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::AudioSystem::AudioSubject";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_attach(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        AudioObserverPrx iceP_obs;
        iceP_userId = istr.readString();
        iceP_obs = AudioObserverPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.attach(iceP_userId, iceP_obs, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_detach(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        obj.detach(iceP_userId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendAudio(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        byte[] iceP_data;
        iceP_fromUser = istr.readString();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.sendAudio(iceP_fromUser, iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_startCall(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.startCall(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_acceptCall(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.acceptCall(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_rejectCall(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.rejectCall(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_hangup(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.hangup(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getConnectedUsers(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String[] ret = obj.getConnectedUsers(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPendingIncomingCalls(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        String[] ret = obj.getPendingIncomingCalls(iceP_userId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPendingAcceptedCalls(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        String[] ret = obj.getPendingAcceptedCalls(iceP_userId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPendingRejectedCalls(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        String[] ret = obj.getPendingRejectedCalls(iceP_userId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPendingEndedCalls(AudioSubject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        String[] ret = obj.getPendingEndedCalls(iceP_userId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "acceptCall",
        "attach",
        "detach",
        "getConnectedUsers",
        "getPendingAcceptedCalls",
        "getPendingEndedCalls",
        "getPendingIncomingCalls",
        "getPendingRejectedCalls",
        "hangup",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "rejectCall",
        "sendAudio",
        "startCall"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_acceptCall(this, in, current);
            }
            case 1:
            {
                return _iceD_attach(this, in, current);
            }
            case 2:
            {
                return _iceD_detach(this, in, current);
            }
            case 3:
            {
                return _iceD_getConnectedUsers(this, in, current);
            }
            case 4:
            {
                return _iceD_getPendingAcceptedCalls(this, in, current);
            }
            case 5:
            {
                return _iceD_getPendingEndedCalls(this, in, current);
            }
            case 6:
            {
                return _iceD_getPendingIncomingCalls(this, in, current);
            }
            case 7:
            {
                return _iceD_getPendingRejectedCalls(this, in, current);
            }
            case 8:
            {
                return _iceD_hangup(this, in, current);
            }
            case 9:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 10:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 11:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 12:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 13:
            {
                return _iceD_rejectCall(this, in, current);
            }
            case 14:
            {
                return _iceD_sendAudio(this, in, current);
            }
            case 15:
            {
                return _iceD_startCall(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
