//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `AudioSubject.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package AudioSystem;

public interface AudioSubjectPrx extends com.zeroc.Ice.ObjectPrx
{
    default void attach(String userId, AudioObserverPrx obs)
    {
        attach(userId, obs, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void attach(String userId, AudioObserverPrx obs, java.util.Map<String, String> context)
    {
        _iceI_attachAsync(userId, obs, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> attachAsync(String userId, AudioObserverPrx obs)
    {
        return _iceI_attachAsync(userId, obs, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> attachAsync(String userId, AudioObserverPrx obs, java.util.Map<String, String> context)
    {
        return _iceI_attachAsync(userId, obs, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_obs -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_attachAsync(String iceP_userId, AudioObserverPrx iceP_obs, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "attach", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeProxy(iceP_obs);
                 }, null);
        return f;
    }

    default void detach(String userId)
    {
        detach(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void detach(String userId, java.util.Map<String, String> context)
    {
        _iceI_detachAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> detachAsync(String userId)
    {
        return _iceI_detachAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> detachAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_detachAsync(userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_detachAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "detach", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, null);
        return f;
    }

    default void sendAudio(String fromUser, byte[] data)
    {
        sendAudio(fromUser, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendAudio(String fromUser, byte[] data, java.util.Map<String, String> context)
    {
        _iceI_sendAudioAsync(fromUser, data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioAsync(String fromUser, byte[] data)
    {
        return _iceI_sendAudioAsync(fromUser, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioAsync(String fromUser, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendAudioAsync(fromUser, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendAudioAsync(String iceP_fromUser, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendAudio", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    default String[] getConnectedUsers()
    {
        return getConnectedUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getConnectedUsers(java.util.Map<String, String> context)
    {
        return _iceI_getConnectedUsersAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getConnectedUsersAsync()
    {
        return _iceI_getConnectedUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getConnectedUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getConnectedUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getConnectedUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getConnectedUsers", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default void startCall(String fromUser, String toUser)
    {
        startCall(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void startCall(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        _iceI_startCallAsync(fromUser, toUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> startCallAsync(String fromUser, String toUser)
    {
        return _iceI_startCallAsync(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> startCallAsync(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        return _iceI_startCallAsync(fromUser, toUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_startCallAsync(String iceP_fromUser, String iceP_toUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                 }, null);
        return f;
    }

    default void acceptCall(String fromUser, String toUser)
    {
        acceptCall(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void acceptCall(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        _iceI_acceptCallAsync(fromUser, toUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> acceptCallAsync(String fromUser, String toUser)
    {
        return _iceI_acceptCallAsync(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> acceptCallAsync(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        return _iceI_acceptCallAsync(fromUser, toUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_acceptCallAsync(String iceP_fromUser, String iceP_toUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "acceptCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                 }, null);
        return f;
    }

    default void rejectCall(String fromUser, String toUser)
    {
        rejectCall(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void rejectCall(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        _iceI_rejectCallAsync(fromUser, toUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> rejectCallAsync(String fromUser, String toUser)
    {
        return _iceI_rejectCallAsync(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> rejectCallAsync(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        return _iceI_rejectCallAsync(fromUser, toUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_rejectCallAsync(String iceP_fromUser, String iceP_toUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "rejectCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                 }, null);
        return f;
    }

    default void hangup(String fromUser, String toUser)
    {
        hangup(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void hangup(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        _iceI_hangupAsync(fromUser, toUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> hangupAsync(String fromUser, String toUser)
    {
        return _iceI_hangupAsync(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> hangupAsync(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        return _iceI_hangupAsync(fromUser, toUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_hangupAsync(String iceP_fromUser, String iceP_toUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "hangup", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioSubjectPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), AudioSubjectPrx.class, _AudioSubjectPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioSubjectPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), AudioSubjectPrx.class, _AudioSubjectPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioSubjectPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), AudioSubjectPrx.class, _AudioSubjectPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioSubjectPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), AudioSubjectPrx.class, _AudioSubjectPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static AudioSubjectPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, AudioSubjectPrx.class, _AudioSubjectPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static AudioSubjectPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, AudioSubjectPrx.class, _AudioSubjectPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default AudioSubjectPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (AudioSubjectPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default AudioSubjectPrx ice_adapterId(String newAdapterId)
    {
        return (AudioSubjectPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default AudioSubjectPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (AudioSubjectPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default AudioSubjectPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (AudioSubjectPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default AudioSubjectPrx ice_invocationTimeout(int newTimeout)
    {
        return (AudioSubjectPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default AudioSubjectPrx ice_connectionCached(boolean newCache)
    {
        return (AudioSubjectPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default AudioSubjectPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (AudioSubjectPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AudioSubjectPrx ice_secure(boolean b)
    {
        return (AudioSubjectPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default AudioSubjectPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (AudioSubjectPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AudioSubjectPrx ice_preferSecure(boolean b)
    {
        return (AudioSubjectPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default AudioSubjectPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (AudioSubjectPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default AudioSubjectPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (AudioSubjectPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default AudioSubjectPrx ice_collocationOptimized(boolean b)
    {
        return (AudioSubjectPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default AudioSubjectPrx ice_twoway()
    {
        return (AudioSubjectPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default AudioSubjectPrx ice_oneway()
    {
        return (AudioSubjectPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default AudioSubjectPrx ice_batchOneway()
    {
        return (AudioSubjectPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default AudioSubjectPrx ice_datagram()
    {
        return (AudioSubjectPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default AudioSubjectPrx ice_batchDatagram()
    {
        return (AudioSubjectPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default AudioSubjectPrx ice_compress(boolean co)
    {
        return (AudioSubjectPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default AudioSubjectPrx ice_timeout(int t)
    {
        return (AudioSubjectPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default AudioSubjectPrx ice_connectionId(String connectionId)
    {
        return (AudioSubjectPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default AudioSubjectPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (AudioSubjectPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::AudioSystem::AudioSubject";
    }
}
